### ISSUE TITLE
set_access_token() should validate the token immediately

### ISSUE THREAD

**Issue by guanidene** [algobulls/pyalgotrading#2]
- Currently, the token is not validated immediately when the token is set. 
- A test API call can be made immediately after setting the token to validate it.

**Comment by prithviraj-gotepatil-algobulls** [comment]
![image](https://github.com/algobulls/pyalgotrading/assets/128346678/99aa0711-fca5-4441-a6b1-442d4ab28ae9)
![image](https://github.com/algobulls/pyalgotrading/assets/128346678/b794226f-b71f-4786-b58c-f640f35e8485)
This is how it will look when this feature will be added.
The test api call that is used here is for getting all strategies.
