### ISSUE TITLE
Following the Pyalgotrading tutorial gives an error

### ISSUE THREAD

**Issue by monk-boop** [algobulls/pyalgotrading#3]
I was following the pyalgotrading tutorial. I copy pasted all the code into strategy_sma_regular_order.py file. When I run the command 'algobulls_connection.create_strategy(StrategySMARegularOrder)' , I get the following error: - 

TypeError: Can't instantiate abstract class StrategySMARegularOrder with abstract methods name

**Comment by guanidene** [comment]
Can you please provide more details, specifically - 
1. The exact code you are trying to run
2. The exact output you are getting

**Comment by guanidene** [comment]
Closing as no response for a long time. Please feel free to re-open this issue if you face any difficulties.
