### ISSUE TITLE
Error while uploading strategy to my AlgoBulls account

### ISSUE THREAD

**Issue by raghavtalwar011** [algobulls/pyalgotrading#5]
<img width="851" alt="Algobulls_Error" src="https://user-images.githubusercontent.com/55542453/104133125-7efbb100-53a7-11eb-968e-0dc850c2eddf.png">

I was trying to upload the strategy EMA Regular order on my algobulls account so that I can perform some backtesting and generate reports according to the tutorial on pyalgotrading repository but there is some constant error which is stopping me from uploading the strategy to my account in the final step. Kindly help me out with it.

**Comment by leoDEVa** [comment]
@raghavtalwar011 have you been able sort the error you are facing since last year sir?

**Comment by akhil-jain-algobulls** [comment]
Hi @raghavtalwar011 and @leoDEVa ,

This issue was resolved long ago. Kindly submit latest error screenshot if you are still facing this error.

**Comment by akhil-jain-algobulls** [comment]
Closing this issue
